#ifndef MACRO_UNREFERENCED_PARAMETER_H_INCLUDED
#	define MACRO_UNREFERENCED_PARAMETER_H_INCLUDED

#define INEX_UNREFERENCED_PARAMETERS( ... )	__VA_ARGS__


#endif // #ifndef MACRO_UNREFERENCED_PARAMETER_H_INCLUDED
