[package]
name = "rust_in_cpp"
version = "0.1.0"
authors = ["PhysShell <schelipov.fedor@yandex.kz>"]
edition = "2018"

[lib]
name = "rust_cpp"
path = "src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
